/*:
 
 # Even Fibonacci numbers
 
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 
 */
import Foundation

var shouldIncrementFirstInt = true
var int1 = 1
var int2 = 2
var sum = 2



var shouldContinueSequence = true
while shouldContinueSequence {
    let newInt = int1 + int2
    if newInt > 4000000 {
        shouldContinueSequence = false
        continue
    }
    
    if newInt % 2 == 0 {
        sum = sum + newInt
    }
    
    if shouldIncrementFirstInt {
        int1 = newInt
        shouldIncrementFirstInt = false
    } else {
        int2 = newInt
        shouldIncrementFirstInt = true
    }
}
    

print("The final sum is \(sum)")






